# yazi.toml
[mgr]
show_hidden = true
ratio = [1,2,3]

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"

[[plugin.prepend_fetchers]]
id    = "mime" # Remove if Yazi > v26.1.22
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"
group = "mime"
